### ISSUE TITLE
BDF 命令行工具执行异常

### ISSUE THREAD

**Issue by changxinchang** [gxdung/U8g2-Font-Convert-For-Arduino#2]
j. 开始转换BDF文件 ( 调用CMD )
 - 当前CMD命令:
 - 显示错误。

**Comment by gxdung** [comment]
请检查字体文件名称是否包含中文字符
Please check if the font file name contains Chinese characters.

**Comment by changxinchang** [comment]
没有中文字符。直接是2.ttf

**Comment by gxdung** [comment]
请检查字体文件的完整性或尝试更换字体

**Comment by changxinchang** [comment]
更换字体还是报错， 一直卡在『 j. 开始转换BDF文件 ( 调用CMD ) 』

**Comment by changxinchang** [comment]
我是在命令提示符里运行的，单独运行 otf2bdf -r 100 -p 16 -o sxt_16.bdf J:\newdownload\arduinoZITI\arduino-u8g2-font-tool-master\font\1.ttf 没报错

**Comment by gxdung** [comment]
> 我是在命令提示符里运行的，单独运行 otf2bdf -r 100 -p 16 -o sxt_16.bdf J:\newdownload\arduinoZITI\arduino-u8g2-font-tool-master\font\1.ttf 没报错

VSCode / Python 运行需要管理员权限且执行路径不得包含空格

**Comment by changxinchang** [comment]
以管理员身份运行的powershell

**Comment by gxdung** [comment]
> 以管理员身份运行的powershell

工具运行目录不得包含空格、字体名称不得包含中文与空格

**Comment by changxinchang** [comment]
改成J:\newdownload\arduinoZITI\u8g2tool。1.ttf。还是报错

**Comment by gxdung** [comment]
> 改成J:\newdownload\arduinoZITI\u8g2tool。1.ttf。还是报错

请附上工具运行截图及字体文件

**Comment by changxinchang** [comment]
![error](https://github.com/user-attachments/assets/04235955-feff-4d42-89cd-6510c3ad392c)
[1.zip](https://github.com/user-attachments/files/16994026/1.zip)

**Comment by gxdung** [comment]
> ![error](https://private-user-images.githubusercontent.com/55017188/367299374-04235955-feff-4d42-89cd-6510c3ad392c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNDA4NTcsIm5iZiI6MTcyNjI0MDU1NywicGF0aCI6Ii81NTAxNzE4OC8zNjcyOTkzNzQtMDQyMzU5NTUtZmVmZi00ZDQyLTg5Y2QtNjUxMGMzYWQzOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE1MTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0N2YwZGRhMDNmOTI3MjNmM2FhYjQ2YjA5NzY0ZmVhZWU4YThjOTY3MGZhMjliYzM3NmFkNzBhZmJjZGMyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L--LI-JEHTlBDOOU2y6evZjITcxeaXft5YVscIgJ1co) [1.zip](https://github.com/user-attachments/files/16994026/1.zip)

该字体可以生成字库文件，请检查开发工具链及依赖库文件。
![image](https://github.com/user-attachments/assets/073302dc-efb6-4d68-bd03-ee052e9035ac)
![image](https://github.com/user-attachments/assets/34e0f987-9d10-4faa-9296-85366e8c82e0)

以下是字库文件：
[U8g2 Fonts.zip](https://github.com/user-attachments/files/16996088/U8g2.Fonts.zip)
